#pragma once

#include <QLabel>
QString lineStyleSheet = "QLineEdit {"
"    padding-right: 5px;"
"    background-color: #212121;"
"    color: #FFFFFF;"
"    font-weight: 600;"
"    border-style: none"
"}";
QString mainButtonStyle = "MyButton {"
"    background-color: #3E3E3E;"
"    color: #FFFFFF;"
"    font-weight: 600;"
"    font-size: 14pt;"
"    border-style: none"
"}"
"MyButton:hover {"
"    background-color: #343434;"
"}";
QString opButtonStyle = "MyButton {"
"    background-color: #343434;"
"    color: #FFFFFF;"
"    font-weight: 600;"
"    font-size: 12pt;"
"    border-style: none"
"}"
"MyButton:hover {"
"    background-color: #3E3E3E;"
"}";
QString memButtonStyle = "MyButton {"
"    background-color: #212121;"
"    color: #FFFFFF;"
"    font-weight: 600;"
"    font-size: 12pt;"
"    border-style: none"
"}"
"MyButton:hover {"
"    background-color: #343434;"
"}";
QString eqButtonStyle = "MyButton {"
"    background-color: #49BAEF;"
"    color: #000000;"
"    font-weight: 600;"
"    font-size: 16pt;"
"    border-style: none"
"}"
"MyButton:hover {"
"    background-color: #8BCDEC;"
"}";
QString specialButtonStyle = "MyButton {"
"    background-color: #49BAEF;"
"    color: #000000;"
"    font-weight: 600;"
"    font-size: 12pt;"
"    border-style: none"
"}"
"MyButton:hover {"
"    background-color: #8BCDEC;"
"}";
QString selButtonStyle = "MyButton {"
"    background-color: #212121;"
"    color: #FFFFFF;"
"    font-weight: 600;"
"    font-size: 16pt;"
"    border-style: none;"
"    width: 1pt;"
"    height: 15pt;"
"}"
"MyButton:hover {"
"    background-color: #3E3E3E;"
"}";
QString sheet = "QLabel {"
"  background-color: transparent;"
"  color: white;"
"  font-size: 12pt;"
"  font-weight: 600;"
"  border: none;"
"}"
"sub {"
"  font-size: 60%;"
"  vertical-align: super;"
"}";
QString menuStyle = "QMenu { menu-scrollable: 1; width: 98px; background-color:#343434; font-size: 15pt }"
"QMenu:item { color: white; margin-left: -1px;}"
"QMenu:item:selected { color: white; background-color: #3E3E3E; }";
QString displayDStyle = lineStyleSheet + QString("QLineEdit{height: 80px; font-size: 34pt}");
QString displayUStyle = lineStyleSheet + QString("QLineEdit{height: 30px; font-size: 10pt; color: #A1A4AA ;}");
QString backStyle = "background-color: #212121;";